lib/osvcd_shared.py

Which did not translate into a proper ipdev scoping in system/svc/vip

Fix the cluster.vip scoped declaration

---

lib/comm.py
lib/svc.py
lib/tests/conftest.py
lib/tests/test_mgr.py
pytest.ini

This will ensure same logic for different Os

Fix RETRYABLE list with errno values

---

.gitignore
tox.ini

It need install tox 'pip install tox'
then run:
tox --parallel auto
or
tox

Add tox config

---

lib/mixinClusterLock.py
lib/node.py
lib/nodedict.py
lib/nodemgr_parser.py
lib/pool.py
lib/poolDorado.py
lib/poolSymmetrix.py
lib/provDiskDisk.py
lib/rcDiskInfo.py
lib/rcDiskInfoHP-UX.py
lib/rcDiskInfoLinux.py
lib/rcDiskInfoSunOS.py
lib/rcDorado.py
lib/resDiskDisk.py
lib/resDiskDiskLinux.py
lib/resScsiReserv.py
lib/resScsiReservSg.py
lib/xmlrpcClient.py
usr/share/doc/template.cluster.array.dorado.conf
usr/share/doc/template.cluster.pool.dorado.conf
usr/share/doc/template.node.array.dorado.conf
usr/share/doc/template.node.dorado.conf
usr/share/doc/template.node.pool.dorado.conf

And fixes for issues discovered during harnessing those drivers.

Dorado array and pool drivers

---

lib/osvcd_shared.py

We only update SMON_DATA (local_expect and global_expect) on changed value.
But keep SMON_DATA[path].global_expect_updated update when global_expect in params.

Small optimisation on osvcd_shared.py

---

bin/pkg/make_man_rst
lib/cfgmgr_parser.py
lib/secmgr_parser.py
lib/svcmgr_parser.py
lib/usrmgr_parser.py

Fix duplicate documentation entries

---

.travis.yml
bin/pkg/make_sunos_pkg
opensvc/drivers/resource/ip/__init__.py
opensvc/tests/resource/ip/test_ip.py

o add next branch to travis builds
o [drivers.resource.ip] Ensure start respect wait_dns duration
o [pkg-SunOS] Ensure run opensvc with python3 if available on system

first merge to next

---

opensvc/core/objects/svc.py

This will ensure unprovision actions in slaves

Service unprovisioning is now propagated to slaves

---

opensvc/drivers/resource/disk/drbd/__init__.py

* Use object nodes instead of all cluster nodes when deploying the drbd res
configuration. Still continue to use all cluster nodes when choosing the
unused and aligned port and minor.
* Refactor the unprovisioner() so the drbd res configuration is deleted even
if drbdadm status reports the resource is not configured.
* Some pep8 fixes.

disk.drbd driver enhancements

---

opensvc/daemon/dns.py

1/
The db cache was indexed by sorted dataset generation numbers (one per node).
So if n1 is at gen 0 and n2 at gen 1, then at next request n2 is at gen 0 and
n1 at gen 1, the same cache key (0, 1) is computed and the dns entries not
recomputed. (this one is far fetched, but doesn't hurt to close the window).
This patch orders the generation numbers by nodename.
2/
The db cache key was computed on set (after entries computation), so if the
dataset changed between the start of computation and the cache set, these
changes would be reflected only after another dataset change, which might be
10 minutes later at most.
This patch compute the cache key before computing the dns db entries, and pass
that key to the cache_set() method. cache_set() no longer computes the key
itself.

Fix two potential dns db desync situation

---

opensvc/core/node/node.py

Assume persistance is expected.

Discard volatile pool from candidates if pool type not requested

---

opensvc/daemon/monitor.py

The provision orchestration sets "wait parent" on secondary instance, but
the local parent instance might never comes up.
Better to wait leader, and let the leader wait parent.

Fix provision orchestration issue with parents=foo@node1

---

opensvc/daemon/clusterlock.py

Without this patch early lock, unlock, lock with same name, may fail

Ensure lock_release returns when lock released in shared.CLUSTER_DATA

---

opensvc/drivers/resource/ip/cni/__init__.py

Detect ip allocations leak in /var/lib/cni/networks/<name>/ on start failures
due to range full. In this situation, purge ip allocations for pid that no
longer exist and retry the cni "add" action.
Also detect the duplicate ip address error, and retry the "add" action once.

Handle two ip.cni driver corner cases

---

opensvc/core/extconfig.py

Broken by the volume#1.mnt deferable reference, overriding the fs#1.mnt
basic keyword reference.

Fix fs#1.mnt reference

---

lib/osvcd_mon.py

* Impacted orchestration of affinity constrained services

Fix KeyError exception

---

opensvc/daemon/dns.py

Instead of trying to map the corresponding nodename.
This avoids a too verbose warning when the cluster.nodes and cluster.dns
are not aligned.
This patch also includes the NS records in the dump and ANY lookup.

Use (ns0, ns1, ...) as the nameserver names in the dns records

---

opensvc/drivers/array/freenas.py

This command did not follow the api v2.0 changes yet.
Also, remove "list iscsi targetgroup", as there no longer is a targetgroup
object independent of a parent target.
Allow "del iscsi target" --name option, in addition to --id.

Fix the "iscsi add targetgroup" command of the freenas driver

---

opensvc/drivers/array/freenas.py

And remove a duplicate method.

Fix the unmap command of the freenas array driver

---

opensvc/daemon/handler_action_helper.py
opensvc/daemon/handlers/node/action/post.py
opensvc/daemon/handlers/object/action/post.py

o Remove unused import_module on object action when cmd is set
o refacto dup code between node and object action handlers

Remove unused import from object action handler

---

opensvc/core/capabilities/__init__.py
opensvc/drivers/resource/container/docker/__init__.py
opensvc/drivers/resource/fs/docker/__init__.py
opensvc/drivers/resource/sync/docker/__init__.py
opensvc/drivers/resource/task/docker/__init__.py
opensvc/utilities/subsystems/docker.py

* do not allow podman let the agent think that docker is available

Improve docker capabilities detection method

---

opensvc/core/node/node.py
opensvc/daemon/handlers/daemon/stats/get.py
opensvc/drivers/resource/app/__init__.py
opensvc/drivers/resource/fs/linux.py
opensvc/drivers/resource/task/__init__.py
opensvc/drivers/resource/task/host/__init__.py

'NoneType' object has no attribute 'split'

Misc fixes and enhancements
