opensvc/opensvc

lib/data.py
os.walk() already recurse subdirs for us, no need to recurse ourselves.
=> Fix the cfg objects add --from <dir> path walking algorithm

lib/node.py, lib/svcmon.py
The "daemon_status" and "events" api handlers accept the namespace option,
but "om mon" did not set this option.
This patch adds the namespace kwarg to the Node::_daemon_status() and Node::
daemon_events() methods, and use that new kwarg in calls from svcmon.
=> Fix "om mon" showing out of current namespace objects

lib/data.py
The "ed" action is now entering the Data::edit() codepath, which fail because
no key is set in options.
Instead of failing, redirect to Data::edit_config(), which is the codepath
that was entered before the "edit --key <k>" action was added.
=> Redirect "om <secpath> ed" to edit config

lib/nodeLinux.py
docker setting the FORWARD chain default policy to DROP, we need to allow
opensvc backend networks.
Use the following pair of rules per net:
-A FORWARD -i obr_net1 -m comment --comment "name: net1" -j ACCEPT
-A FORWARD -o obr_net1 -m comment --comment "name: net1" -j ACCEPT
=> Allow forwarding to the opensvc backend networks

lib/osvcd_lsnr.py
In a fast succession of events, a n+1 event could overwrite the n event data
for a client.
Make a copy of the dequeue event before putting the copy in the client queue,
to avoid being replaced while queued.
=> Fix an issue in event delivery to clients

lib/resTaskDocker.py
Use the resTask start/stop method instead of the resContainer implementation.
As the resTaskDocker class inherits from the resTask and the resContainerDocker
driver, explicitely choose the start/stop implementation to use.
=> Don't start/stop task.type=oci containers on start/stop

lib/resFs.py, lib/resFsDir.py, lib/svc.py
Catch AttributeError from resFs __lt__ when comparing mount_point attrs, as
this attribute may not exist in all fs drivers (ex: fs.flag).
Resync the resFsDir __lt__ definition from resFs.
Do not return the first fs resource mount point as the volume mount point, as
the first fs resource might not have a mount_point attribute. Return the
mount point of the first fs resource with a mount_point attribute instead.
=> Fix a stack sorting fs.dir and fs.flag resources in the same object

lib/extconfig.py, lib/hb_ucast.py, lib/rcUtilities.py
At least data section needs to store keys in secrets and configmaps respecting
user-intended naming (like file names and path).
=> Allow Uppercase in config file keys

lib/node.py
om node daemon relay status --server raw://relay.opensvc.com
=> Fix relay query when --node option is not set

lib/resScsiReserv.py, lib/resScsiReservSg.py
Example:
With 1 registration down on 1/2 luns, we reported 1/4 instead of 3/4
root@ringfs-1:/opt/opensvc# om test/svc/svc100 print status -r
test/svc/svc100                   warn       warn
`- instances
`- ringfs-1                    warn       warn, frozen, idle
|- disk#0          ........ down       vg svc100.test.svc.ringfs
`- disk#0pr        ........ warn       /dev/sde, /dev/sdh, /dev/sdp, /dev/sds
warn: 1/4 paths registered
=> Fix the scsireserv registered count for multi-lun resources

lib/resScsiReservSg.py
Increment the registered counter instead of resetting it for each disk.
And pass a list to mangle_devs() instead of a string.
=> Fix the test for registration keys count

lib/pool.py, lib/poolDirectory.py, lib/poolDorado.py, lib/poolFreenas.py, lib/poolLoop.py, lib/poolShare.py, lib/poolShm.py
Instead of the previous incomplete white-list implementation.
For example, a xfs over dorado volume had its sync#i0 active with the
previous implementation.
=> Disable volume sync#i0 if it contains no resource with files to sync

lib/nodeLinux.py
1/ don't log we failed to crash for TOC when we actually tried to reboot.
2/ remove duplicate sleep(1) + node freeze in the reboot TOC codepath
3/ strip the sysrq mask read from file before logging, so we dont end up
with a multiline message.
=> TOC fixes and enhancements on Linux

lib/resScsiReserv.py, lib/resScsiReservFreeBSD.py, lib/resScsiReservLinux.py, lib/resScsiReservOSF1.py, lib/resScsiReservSg.py
Detect mpathpersist presence and prefer it over sg_persist.
The sg_persist is then no longer necessary, the codebase using mpathpersist
for all commands.
OpenSVC doesnt set the defaut.reservation_key=file in multipath.conf. This
is important to set it to activate the register-path-before-add-to-multipath
feature of multipathd, which prevents ioerrs on registered multipath when
one of the active paths is not registered.
Even if defaut.reservation_key=file is not set, the mpathpersist commands we
execute produce the same registration and reservation as with sg_perist.
=> Add mpathpersist support

lib/cfg.py, lib/data.py, lib/sec.py
It might be valid to expose an empty environment variable to a container.
Also it is frequent to find empty files in a file tree imported in a sec or
cfg. In this case, before this patch, the "om <secpath> add --from <head>"
failed when trying to add the key with empty value, leaving the file tree
partially imported.
=> Allow empty sec and cfg keys value

lib/rcLogger.py, lib/resources.py, lib/resourceset.py, lib/svc.py
Object actions run by the scheduler set "sc:y", normal actions set "sc:n".
So log viewers can easily filter out scheduled action logs, to focus on
manual and orchestrated actions.
=> Add the "sc" metadata to objects log lines

lib/handlerPostObjectAction.py, lib/handlerPostObjectCreate.py
File "/opt/opensvc/lib/osvcd_lsnr.py", line 1172, in h2_router
result = self.router(None, data, stream_id=stream_id, handler=handler)
File "/opt/opensvc/lib/osvcd_lsnr.py", line 1816, in router
handler.rbac(nodename, action=action, options=options, stream_id=stream_id, thr=self)
File "/opt/opensvc/lib/handlerPostObjectCreate.py", line 80, in rbac
if errors:
AttributeError: 'ClientHandler' object has no attribute 'rbac_create_data'
=> Fix http2 api create object error (wrong function call)

lib/rcOptParser.py
/opt/opensvc/lib/rcOptParser.py:312: SyntaxWarning: "is" with a literal. Did you mean "=="?
if len(args) is 0:
=> Fix a py 3.8 warning

lib/data.py
These keys decode() return binary data, so we need to decode() the read buffer
before searching linesep into it.
If we can't decode, raise an informative error stating the key is not editable:
no need to display a binary in a text editor.
=> Fix "om <sec> edit --key ..." on py3 for keys injected from file

lib/resIpCni.py
And catch locking errors. Escalate them as Error.
=> Set a longer timeout for the cni global lock acquire on ip.cni start

lib/osvcd_shared.py
For example, we want to persist the ip#0 "noaction" tag when the vip is an ip
address managed by the operating system.
=> Allow user-defined system/svc/vip ip#0.tags to persist

lib/osvcd_shared.py
This new key holds the timestamp of the last OsvcThread::reload_config()
succesful execution.
So it can be used to wait for a change to be honored to continue a batch.
For example:
$ om cluster set --kw env.foo=bar ; \
date ; \
om node wait --filter "monitor.configured>$(om cluster print config mtime)" ; \
date
mer. 20 mai 2020 12:28:23 CEST
mer. 20 mai 2020 12:28:29 CEST
This patch is a backport of 41bfde13f0f1a90a667deb4ff08682d54b7e9fcd.
=> Add a configured key to each daemon thread status dataset

.travis.yml, opensvc/drivers/resource/app/simple/sunos.py
commit 5f88e217436dfb0c919d4ba2853a5abed578ca45 already fix default implementation
with following commit message:
Add a validate=True|False to get_cmd(), so app.simple can set validate=False
in the get_matching codepath and not be disrupted when the referenced script
is not accessible (the holding fs resource might be down).
=> Fix app.simple stop when the script is not accessible (Solaris Only)

opensvc/core/extconfig.py
Before: {"error": "local variable 'val' referenced before assignment"}
Now:    {"error": "DEFAULT.start_timeout not found in the keywords dictionary"}
=> Update diag message when 'print config --eval' has errors

lib/rcUtilities.py
The action trigger did not accept the "on_error" trigger name
used by the task.host driver.
=> Fix ignored tasks "on_error" trigger

opensvc/drivers/resource/ip/__init__.py, opensvc/drivers/resource/ip/host/sunos.py, opensvc/tests/resource/ip/test_ip_host_sunos.py
Avoid use of ifconfig ... netmask +
Instead use detected netmask value
Reason:
netmask + use detected net networks in /etc/inet/netmask
when network is not found in netmask file, ifconfig netmask +
will set netmask from standard ip classes
This may lead to start ip with incorrect netmask, and then
have a service print status that complain about invalid netmask
test_ip_host_sunos.TestIpStartCmd
o test_call_ifconfig_with_correct_netmask_value[net0-255.255.255.0]
o test_call_ifconfig_with_correct_netmask_value[net1-255.255.0.0]
o test_call_ifconfig_with_correct_netmask_value[net2-255.0.0.0]
=> [drivers.resource.ip.host] Fix netmask value for Solaris

opensvc/drivers/resource/ip/host/sunos.py, opensvc/tests/resource/ip/test_ip_host_sunos.py
It didn't respect anymore respect netmask keyword value from service ip config
The regression was introduce by 4605f672a67e1fef1475ba8870d2e30fc2d5eea1 [drivers.resource.ip.host] Fix netmask value for Solaris)
=> [drivers.resource.ip.host] Fix regression in netmask value for Solaris

opensvc/utilities/version/__init__.py
On an install from git, and when a new tag is created on the HEAD, the split
on '-' returns only one element, which causes an IndexError.
=> Fix a stack in utilities.version

opensvc/utilities/devtree/sunos.py
When pool is FAULTY, we can not extract its dev info
o zpool status faultypool output:
pool: faultypool
state: UNAVAIL
status: One or more devices are unavailable in response to persistent errors.
There are insufficient replicas for the pool to continue functioning.
action: Destroy and re-create the pool from a backup source. Manually marking
the device repaired using 'zpool clear' or 'fmadm repaired' may
allow some data to be recovered.
Run 'zpool status -v' to see device specific details.
scan: none requested
config:
NAME                     STATE      READ WRITE CKSUM
tpool                    UNAVAIL       0     0     0
mirror-0               UNAVAIL       0     0     0
/file1               UNAVAIL       0     0     0
3050059147443554189  UNAVAIL       0     0     0
errors: No known …
=> Fix om node print devs stack when FAULTY zpool exists (Solaris)

opensvc/drivers/resource/disk/drbd/__init__.py, opensvc/drivers/resource/task/__init__.py
The unprovision orchestration execute a "stop --force" on the up instances
before "unprovision". The drbd driver did not "down" the drbd device, so
the stop on the underlying lv failed.
=> Honor "stop --force" in the drbd driver

opensvc/daemon/handlers/object/confirmations/get.py
So the webapp can ask for run confirmation for the reported resources.
This handler requires the operator privilege on the requested object.
=> Add the GET /object_confirmations handlers

opensvc/daemon/monitor.py
Remove lock and don't stop iterating on irrelevant KeyError.
=> Fix and optimize daemon monitor get_local_paths()

opensvc/core/node/nodedict.py, opensvc/core/pool.py
If set, the volume objects created from the pool will have their
DEFAULT.status_schedule set to this value.
=> Add a pool "status_schedule" keyword

opensvc/drivers/resource/container/docker/__init__.py
Do not arm a signal if the task has no timeout.
=> Fix a stack with task.docker and task.podman when no timeout is set

.travis.yml
This should fix following error:
$ pytest --cov -m "ci"
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
plugin = ep.load()
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2410, in load
self.require(*args, **kwargs)
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in require
items = working_set.resolve(reqs, env, installer, extras=self.extras)
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest …
=> [travis] Move to focal to avoid pytest error

opensvc/drivers/resource/container/__init__.py
When the first namespace is not available the glibc udp dns request will
have to wait until timeout*attemps before trying the next nameserver, which
is 10s by default and 1s minimum (timeout:1 attempts:1).
Setting the use-vc option forces a tcp request instead of a udp request.
A tcp request will fail immediately if the nameserver is down.
Note: alpine's musl libc is not affected by this issue as it requests all
defined nameservers and returns the first response. But setting use-vc there
too is ok.
=> Set use-vc in resolv.conf options for containers using backend ipaddr

opensvc/core/objects/svc.py, opensvc/core/resource.py, opensvc/drivers/resource/ip/__init__.py
A consequence of this corruption for ip resource, which resource info contains
the ipaddr used in the dns db, the service dns records are dropped until the
next status refresh (may be up to 10m).
On peer node label changes the daemon triggers a refresh=False rewrite of the
services status.json, so all keys depending on labels are updated, but not
reevaluating the resources status. The resource dataset are fetched from the
resource status.last cache, which did not include the "info" key, causing a
loss of information.
This patch add the "info" key to status.last, and restore this cached
information on print_status_data_eval(refresh=False,...).
=> Fix a resource info corruption on peer node labels change

opensvc/drivers/resource/container/docker/__init__.py, opensvc/utilities/subsystems/docker.py
A new container.docker and container.podman keyword "registry_creds" can be
set in the resource or/and in DEFAULT to the name of a secret in the same
namespace.
If this secret contains a config.json key, which value is the content of
the config.json generated by a "docker login <registry dnsname>".
For example, the creds secret can be created by:
om test/sec/creds-registry-opensvc-com create
om test/sec/creds-registry-opensvc-com add --from ~/.docker/config.json
Upon container start and pull, the appropriate command option is added to
point an up-to-date projection of the config.json.
With podman --authfile, with docker --config.
=> Support registry creds config as secrets

bin/pkg/makelib.sh
Now that the templates are no longer tracked with the code, we need to
generate them in the build sandbox before creating the package.
=> Fix missing templates in usr/share/doc

opensvc/drivers/resource/container/docker/__init__.py
Only applicable to pull and run commands.
=> Don't set registry creds option on docker/podman start commands

opensvc/core/capabilities/__init__.py
Without this node.x.podman capability is not detected and container.type oci may use docker instead of podman
=> [container.oci] Fix podman location

bin/pkg/make_deb
qau20c26n2/opt/opensvc/bin/pkg/make_deb: line 10: cd: /opt/opensvc/bin/pkg/../../tmp/BUILDROOT/opensvc-2.1-94/..: No such file or directory
=> Fix error message in make_deb

opensvc/core/objects/svc.py
Missing lazy unset of Svc::flex_target in Svc::unset_conf_lazies(), which
is called on labels change events.
=> Fix flex_target not updated on node labels change

opensvc/daemon/shared.py, opensvc/tests/daemon/test_shared.py
Even if add_cluster_node is not anymore called with empty nonename,
we prefer fix possible future invalid calls
stack:
ERROR n:node-0 c:listener/local | sequence item 1: expected str instance, NoneType found
File "/usr/share/opensvc/opensvc/daemon/listener.py", line 1160, in h2_router
result = self.router(None, data, stream_id=stream_id, handler=handler)
File "/usr/share/opensvc/opensvc/daemon/listener.py", line 1816, in router
return handler.action(nodename, action=action, options=options, stream_id=stream_id, thr=self)
File "/usr/share/opensvc/opensvc/daemon/handlers/join/post.py", line 24, in action
data = self.join(nodename, thr=thr, **kwargs)
File "/usr/share/opensvc/opensvc/daemon/handlers/join/post.py", line 34, in join …
=> Fix listener crash during invalid daemon join call

opensvc/core/comm.py
Stack example:
E set monitor status failed: '<' not supported between instances of 'int' and 'NoneType'
File "/usr/share/opensvc/opensvc/core/comm.py", line 790, in h2_daemon_request
conn.request(method, path, headers=headers, body=body)
File "/usr/share/opensvc/opensvc/foreign/hyper/http20/connection.py", line 274, in request
self.endheaders(message_body=body, final=True, stream_id=stream_id)
File "/usr/share/opensvc/opensvc/foreign/hyper/http20/connection.py", line 575, in endheaders
stream.send_headers(headers_only)
File "/usr/share/opensvc/opensvc/foreign/hyper/http20/stream.py", line 99, in send_headers
self._send_outstanding_data()
File "/usr/share/opensvc/opensvc/foreign/hyper/http20/connection.py", line 486, in _send_outstanding_data …
=> Fix stack from crm when daemon is not restarting

opensvc/core/node/node.py
Add missing convert duration for request timeout
This fix following stack:
File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/share/opensvc/opensvc/__main__.py", line 118, in <module>
ret = main()
File "/usr/share/opensvc/opensvc/__main__.py", line 91, in main
ret = main(argv=sys.argv[2:])
File "/usr/share/opensvc/opensvc/commands/node/__init__.py", line 65, in main
return _main(node, argv=argv)
File "/usr/share/opensvc/opensvc/commands/node/__init__.py", line 45, in _main
err = node.action(action)
File "/usr/share/opensvc/opensvc/core/node/node.py", line 1074, in action
return self._action(action, …
=> Fix 'om node drain --wait' error

opensvc/commands/daemon/__init__.py, opensvc/core/node/node.py, opensvc/tests/commands/daemon/test_daemon.py
Call 'om daemon start' does restart opensvc daemon if daemon is already running.
Now call 'om daemon start' when daemon is already running simply return without actions.
=> Fix 'om daemon start' when daemon is already running

lib/svc.py
Rewrite Svc::__push_encap_config() for readbility, and plug a sanity check
function analyzing the pulled configuration file.
Also don't overwrite the configuration file on the global. Pull into a
temporary file instead, to run the sanity checks, then install with an
atomic rename if checks passed.
=> Don't install empty svc config from encap into the global

opensvc/core/node/linux.py
When the device with the lowest mac is removed from the bridge or when
a new device with the lowest mac is added to the bridge, all containers
can experience tcp hangs while the arp table resynchronizes.
Setting a mac address to the bridge explicitely avoids these mac address
changes.
Forge the mac address using a 0a:58 prefix followed by the bridge ipv4
address converted to hexa (same algorithm used in k8s).
Plug the mac addr setting in the "om net setup" codepath. Incrementally
configure it, so it will be set upon upgrade for bridge created before
this patch.
Example:
root@demo2:~# om net set
@ n:demo2
ip link set dev obr_net1 address 0a:58:0a:21:04:01
ip route replace 10.33.0.0/22 via 5.196.34.153 table main
ip route replace 10.33.4.0/22 dev obr_net1 table main
=> Fix tcp ~15s hangs in containers tcp connections

opensvc/drivers/resource/container/docker/__init__.py
The stack was:
File "/opt/opensvc/opensvc/drivers/resource/container/docker/__init__.py", line 566, in registry_creds_sec
return factory("sec")(self.registry_creds, namespace=self.svc.namespace, volatile=True)
File "/opt/opensvc/opensvc/core/objects/svc.py", line 503, in __init__
self.path = fmt_path(self.name, self.namespace, self.kind)
File "/opt/opensvc/opensvc/utilities/naming/__init__.py", line 183, in fmt_path
return "/".join((kind, name))
=> Fix image pulling when no registry_creds is specified

opensvc/daemon/handlers/node/action/post.py
This action would report unset "node" option even if set in the request
payload, because it deletes it thinking its a request routing information.
Make sure we preserve the "node" option for actions that use it, ie
daemon_join and daemon_rejoin.
=> Fix the "daemon_join" action via the POST /node_action handler

opensvc/daemon/handlers/object/create/post.py
The 'data' option documentation only described its content when used without
the 'template' option.
=> Document env section override via 'data' option in POST /object_create

opensvc/daemon/handlers/node/action/post.py
Add the data.pid and data.session_id keys to the result.
Pass the session_id and cmd to push_proc, so node_action process can be filtered
by session_id via the GET /daemon_actions handler.
Example:
$ echo '{"method": "POST", "action": "node_action", "options": {"action": "compliance_check", "sync": false}}' | sudo socat -t15 - /opt/opensvc/var/lsnr/lsnr.sock|jq
{
"status": 0,
"data": {
"pid": 317463,
"session_id": "5bf844bd-f4be-4315-8c42-c215a50da488"
},
"info": "started node action compliance_check --local"
}
$ echo '{"method": "GET", "action": "daemon_actions", "options": {"thread": "listener"}}' | sudo socat -t15 - /opt/opensvc/var/lsnr/lsnr.sock|jq
{
"status": 0,
"data": [
{
"thread": "listener",
"pid": 317463,
"session_id": "5bf844bd-f4be-4315-8c42-c215a50da488",
"cmd": [ …
=> Align the POST /node_action result with POST /object_action

lib/fmt_cluster.py, lib/hb.py, lib/osvcd_mon.py
The init phase can exit before all instances status is refreshed. Causing
the other nodes to think they can start their own instance.
Backport from b2.1 the patches changing the daemon init phase so it allows
sending the node data with partial service instance status information.
This patch include a refactor of the init phase exit conditions, strictly
verifying that instances have their status loaded.
=> Fix undue instance start on peer daemon upgrade

opensvc/daemon/hb/hb.py, opensvc/utilities/render/cluster/__init__.py
Represent this attribute as "?" after the preserved availstatus.
For example: "up | O? X" is an expected "<agg> | <status> <status>" pattern
seen from node2 when node1 daemon is in the init stage.
Which is better than the current "down | ? X" transient state, with regards
to alarming.
=> Add a per-instance "preserved" attribute in the status structure

opensvc/core/objects/cfgdict.py, opensvc/core/objects/secdict.py, opensvc/core/objects/svcdict.py, opensvc/core/objects/usrdict.py
Without this patch, the following config produces an error :
[expose#1]
type = envoy
listener_certificates = certificate#0
...
=> Add the comment keyword in all data sections

opensvc/core/objects/svc.py
The agent logs the command, and the log function interprets the % as a
substitution wildcard.
Example:
om testvg1 update \
--resource '{"rtype": "disk", "type": "lv", "vg": "{svcname}", "size": "100%FREE", "name": "root"}' \
--disable-rollback
=> Fix a warning stack on svc action when args contain a "%"

opensvc/drivers/array/freenas.py, opensvc/drivers/pool/freenas.py
The pool data is still not returned by api 2.0.
Use api 1.0 for that.
With this patch, it is no longer needed to set the full path in the api
keyword value of the array section.
=> Fix the freenas pool driver

opensvc/core/node/nodedict.py, opensvc/daemon/hb/disk.py, opensvc/daemon/hb/hb.py, opensvc/daemon/hb/mcast.py, opensvc/daemon/hb/relay.py, opensvc/daemon/hb/ucast.py
To allow users to change from the 3s default.
Lowering the interval permits to lower the "timeout" from the default 15s,
and the "node.ready_period" from the default 5s.
This kind of tuning can be used on clusters with few data-less services
that need fast recovery (4s minimum).
Example:
[node]
ready_period = 2s
[hb#1]
type = unicast
timeout = 2s
interval = 1s
=> Add the "interval" option to all heartbeat drivers configuration syntax

opensvc/core/objects/svc.py, opensvc/core/resource.py, opensvc/core/scheduler.py
This is an issue because the ip info contains the ipaddr exposed via the
cluster dns. So the ip resource could lose the resolution on run actions
if a resolution query is submitted during the run action.
This patch moves the Resource::status_info() call out of Svc::status_data_eval()
to Resource::status(), so everytime status() refreshes the main status data it
also updates the status_info() and updates the cache. Which garanty the
last_status_data cache file contains a valid "info" section.
=> Fix a resource info clear issue at the begining of tasks run action

opensvc/drivers/resource/fs/flag/__init__.py, opensvc/tests/utilities/fixture-site/site-opensvc/drivers/resource/fs/sitea/__init__.py, opensvc/tests/utilities/fixture-site/site-opensvc/drivers/resource/fs/sitea/linux.py, opensvc/tests/utilities/fixture-site/site-opensvc/drivers/resource/fs/siteb/__init__.py, opensvc/tests/utilities/fixture-site/site-opensvc/drivers/resource/sitegrp/__init__.py, opensvc/tests/utilities/test_driver.py, opensvc/utilities/drivers.py
With this update module import search is now the following
1- internal opensvc drivers
2- site opensvc drivers
3- fallback internal opensvc drivers
4- fallback to site opensvc drivers
Also update BaseFsFlag.__init__ definition to provide simpler
site drivers examples based on fs.flag type:
Example: site-opensvc/drivers/resource/fs/siteflag/linux.py
```
import os
from drivers.resource.fs.flag.linux import FsFlag
from utilities.lazy import lazy
DRIVER_GROUP = "fs"
DRIVER_BASENAME = "customflag"
class FsCustomflag(FsFlag):
def __init__(self, **kwargs):
super(FsCustomflag, self).__init__(type="fs.customflag", **kwargs)
@lazy
def base_flag_d(self):
return os.path.join(os.sep, "dev", "shm", "custom-flag")
```
=> Update driver import search order for site-opensvc drivers

opensvc/core/objects/vol.py, opensvc/drivers/resource/volume/__init__.py, opensvc/utilities/asset/asset.py
Don't try to stop a volume instance from a user's instance stop if other user
instances are running.
=> Fix undue volume instance stop on user instance's stop

lib/nodeSunOS.py
Because swap -l add extra 'encrypted' computation of avail and swap size is now incorrect
This commit fix following stack:
Exception in thread monitor:
File "/opt/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/share/opensvc/lib/osvcd_mon.py", line 146, in run
self.init()
File "/usr/share/opensvc/lib/osvcd_mon.py", line 142, in init
self.update_hb_data()
File "/usr/share/opensvc/lib/osvcd_mon.py", line 3268, in update_hb_data
self.update_cluster_data()
File "/usr/share/opensvc/lib/osvcd_mon.py", line 3204, in update_cluster_data
self.update_node_data()
File "/usr/share/opensvc/lib/osvcd_mon.py", line 3223, in update_node_data
data["stats"] = shared.NODE.stats()
File "/usr/share/opensvc/lib/node.py", line 5095, in …
=> Fix stats_meminfo error on Solaris 11.4

opensvc/tests/test_converters.py, opensvc/utilities/converters/__init__.py
This patch fix following stack
$ om node checks
File "/usr/share/opensvc/opensvc/utilities/converters/__init__.py", line 295, in convert_size
start_idx = l.index(unit)
ValueError: 'B' is not in list
During handling of the above exception, another exception occurred:
File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/share/opensvc/opensvc/__main__.py", line 124, in <module>
ret = main()
File "/usr/share/opensvc/opensvc/__main__.py", line 97, in main
ret = main(argv=sys.argv[2:])
File "/usr/share/opensvc/opensvc/commands/node/__init__.py", line 65, in main
return …
=> Accept 'B' unit during convert_size

opensvc/drivers/resource/container/docker/__init__.py
This provisioner method pre-pull the image on non leader nodes if the
docker_daemon_private=false (default).
=> Add a non-leader provisioner to docker/podman resources

opensvc/tests/daemon/monitor/test_orchestrator_start.py
test_orchestrator_from_init_to_run_loop:
o [parent avail - /has start/, /start failed/-svcnames0-s-depend-on-parent-other_node_status0-ready-starting-start failed]
o [local frozen, simple parent avail - stay idle, /no start/-svcnames1-s-depend-on-parent-other_node_status1-idle-idle-idle]
o [simple parent avail - /has start/-svcnames2-s-depend-on-parent-other_node_status2-ready-starting-idle]
o [parent avail unknown - stay in wait parents /no start/-svcnames3-s-depend-on-parent-other_node_status3-wait parents-wait parents-wait parents]
o [/no node2 status/, plop must stay in wait parent, /no start/, /node frozen/-svcnames4-s-depend-on-parent-other_node_status4-idle-idle-idle]
o [not enough flex - stay in wait parents, /no start/-svcnames5-s-depend-on-parent-flex-min-2-other_node_status5-wai …
=> Add more tests on monitor do()

opensvc/drivers/array/hcs.py
Typo in driver array/hcs.py, action list_host_groups cause "not implemented" result
=> Fix driver array/hcs.py, action "list host groups"

opensvc/core/objects/svc.py, opensvc/daemon/handlers/node/action/post.py, opensvc/daemon/handlers/object/action/post.py, opensvc/utilities/render/command.py
Some codepath, notably volume creation, submit object actions programmatically
(ex. volume.action("stop", ...)) instead of via a executed CRM
command, causing the secondary object to log the sys.argv of the original
command (ex. om <svc> provision).
This patch uses the POST /object/action and POST /node/action handlers
code to format the command to log from (parser, action, options) inputs.
This code now being used by the daemon and the CRM, host it in the
utilities.render.command module.
=> Fix wrong "do <action> <option>" log

opensvc/tests/resource/disk/drbd/test_drbd.py
drbdadm_connect_discard() has been renamed to drbdadm_connect
=> [test] Fix drbd test since --discard-my-data not always used

opensvc/core/resource.py
When a service has a ip resource with tags=noaction, the unprovisioner cannot
run, so the provisioned state of the resource will stay "true" and cause an
unprovision action loop.
This patch return a "None" resource provisioned state (not applicable) for
resource tagged "noaction".
Beware, at least one resource must have a valid provisioned state (a fs.flag
if nothing else).
=> Fix a unprov orchestration loop situation
